apiVersion: v2
name: cert-manager-wrapper
version: 1.0.0

dependencies:
  - name: cert-manager
    version: "1.19.1"     # use the version you saw from helm search repo
    repository: "https://charts.jetstack.io"