{{- if .Values.ingressClassParameters.enabled }}
apiVersion: "ingress.oraclecloud.com/v1beta1"
kind: IngressClassParameters
metadata:
  name: native-ic-params
  namespace: native-ingress-controller-system
spec:
  compartmentId: "{{ .Values.ingressClassParameters.compartmentId }}"
  subnetId: "{{ .Values.ingressClassParameters.subnetId }}"
  loadBalancerName: "{{ .Values.ingressClassParameters.loadBalancerName }}"
  isPrivate: false
  maxBandwidthMbps: 400
  minBandwidthMbps: 100
{{- end }}